version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: no
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
